// 해파리 피하기 게임: 해파리는 피하고, 바다 쓰레기는 수거해 보너스 점수를 얻습니다.
window.SeaGames = (() => {
  let canvas, ctx, running = false, animation, keys = {}, player, objects = [], particles = [];
  let score = 0, collected = 0, startedAt = 0, lastSpawn = 0, lastFrame = 0, countdownTimer, flash = '', flashLife = 0;
  // 위험도 예시 데이터에 맞춘 게임 규칙: 해파리·파도 장애물의 등장 비율이 지역마다 다릅니다.
  const courses = { gwangalli: { name: '광안리', speed: .88, jelly: .38, wave: 0, sky: ['#84d7f1', '#d9f7ff'], sea: ['#38b4d9', '#0576ae'], photo: 'assets/gwangalli.jpg', feature: '광안대교가 펼쳐지는 부산의 대표 도심 해변', credit: 'Photo: Chelsea Hicks · CC BY 2.0 (Wikimedia Commons)' }, songjeong: { name: '송정', speed: 1, jelly: .55, wave: .18, sky: ['#a0c8ff', '#e4efff'], sea: ['#299bc8', '#075494'], photo: 'assets/songjeong.jpg', feature: '완만한 모래사장과 서핑 문화가 어우러진 해변', credit: 'Photo: Andrewssi2 · CC BY-SA 3.0 (Wikimedia Commons)' }, dadaepo: { name: '다대포', speed: 1.16, jelly: .30, wave: .42, sky: ['#83d6ef', '#dcf7ff'], sea: ['#32b1d2', '#0576ae'], photo: 'assets/dadaepo-sea.jpg', feature: '낙동강 하구와 넓은 백사장이 펼쳐진 낮의 해변', credit: 'Photo: Ken Eckert · CC BY-SA 4.0 (Wikimedia Commons)' } };
  let course = courses.gwangalli;
  const $ = id => document.getElementById(id);
  function beep(frequency = 440) { try { const audio = new (window.AudioContext || window.webkitAudioContext)(); const osc = audio.createOscillator(); const gain = audio.createGain(); osc.frequency.value = frequency; gain.gain.value = .035; osc.connect(gain); gain.connect(audio.destination); osc.start(); osc.stop(audio.currentTime + .07); } catch (_) {} }
  function init() { canvas = $('gameCanvas'); ctx = canvas.getContext('2d'); document.addEventListener('keydown', event => { if (['ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown'].includes(event.key)) { keys[event.key] = true; if (running) event.preventDefault(); } }); document.addEventListener('keyup', event => keys[event.key] = false); document.querySelectorAll('[data-move]').forEach(button => { const key = { left: 'ArrowLeft', right: 'ArrowRight', up: 'ArrowUp', down: 'ArrowDown' }[button.dataset.move]; ['pointerdown', 'pointerup', 'pointerleave', 'pointercancel'].forEach(event => button.addEventListener(event, () => keys[key] = event === 'pointerdown')); }); }
  function choose(courseName) { course = courses[courseName] || courses.gwangalli; $('gameChoice').classList.add('hidden'); $('gameStage').classList.remove('hidden'); $('gameTitle').textContent = `서퍼와 함께 · ${course.name}`; $('scoreLabel').innerHTML = '점수 <b id="score">0</b>'; $('extraLabel').innerHTML = '수거 <b id="best">0</b>'; start(); }
  function backToChoices() { stop(); $('gameStage').classList.add('hidden'); $('gameChoice').classList.remove('hidden'); }
  function showCountdown(number) { const counter = $('countdown'); const text = number > 0 ? number : 'START!'; counter.style.backgroundImage = `url("${course.photo}")`; counter.innerHTML = `<div class="countdown-copy"><small>${course.name} SURF COURSE</small><strong>${text}</strong><p>${course.feature}</p><em>${course.credit}</em></div>`; }
  function start() { stop(); score = 0; collected = 0; objects = []; particles = []; flash = ''; flashLife = 0; player = { x: 110, y: canvas.height / 2 }; $('gameOver').classList.add('hidden'); $('score').textContent = '0'; $('best').textContent = '0'; let number = 3; const counter = $('countdown'); counter.classList.remove('hidden'); showCountdown(number); beep(); countdownTimer = setInterval(() => { number--; showCountdown(number); beep(number > 0 ? 440 : 660); if (number < 0) { clearInterval(countdownTimer); counter.classList.add('hidden'); running = true; startedAt = performance.now(); lastFrame = startedAt; animation = requestAnimationFrame(loop); } }, 680); }
  function stop() { running = false; cancelAnimationFrame(animation); clearInterval(countdownTimer); }
  function loop(now) { if (!running) return; const delta = Math.min(40, now - lastFrame); lastFrame = now; update(delta, now); draw(now); animation = requestAnimationFrame(loop); }
  function update(delta, now) { const elapsed = (now - startedAt) / 1000; const step = 5.5 * delta / 16; if (keys.ArrowLeft) player.x -= step; if (keys.ArrowRight) player.x += step; if (keys.ArrowUp) player.y -= step; if (keys.ArrowDown) player.y += step; player.x = Math.max(42, Math.min(canvas.width - 42, player.x)); player.y = Math.max(140, Math.min(canvas.height - 38, player.y)); const interval = Math.max(250, 720 - elapsed * 19); if (now - lastSpawn > interval) { spawn(elapsed); lastSpawn = now; } objects.forEach(item => item.x -= (item.speed + elapsed * .075) * delta / 16); particles.forEach(p => { p.x += p.vx; p.y += p.vy; p.life--; }); particles = particles.filter(p => p.life > 0); if (flashLife) flashLife--; for (let i = objects.length - 1; i >= 0; i--) { const item = objects[i]; if (Math.abs(item.x - player.x) < 36 && Math.abs(item.y - player.y) < 32) { objects.splice(i, 1); if (item.kind === 'jelly' || item.kind === 'wave') { end(item.kind); return; } collected++; score += 5; $('score').textContent = score; $('best').textContent = collected; flash = '+5 CLEAN!'; flashLife = 28; burst(item.x, item.y, '#ffe266'); beep(720); continue; } if (item.x < -55) { if (item.kind === 'jelly') { score++; $('score').textContent = score; } objects.splice(i, 1); } } }
  function spawn(elapsed) { const roll = Math.random(); let kind; if (roll < .25) kind = ['bottle', 'can', 'bag'][Math.floor(Math.random() * 3)]; else if (roll < .25 + course.wave) kind = 'wave'; else if (roll < .25 + course.wave + course.jelly) kind = 'jelly'; else return; objects.push({ kind, x: canvas.width + 55, y: 145 + Math.random() * (canvas.height - 190), speed: (3.4 + elapsed * .14 + Math.random() * 2.2) * course.speed }); }
  function burst(x, y, color) { for (let i = 0; i < 12; i++) { const a = Math.random() * Math.PI * 2; particles.push({ x, y, vx: Math.cos(a) * (1 + Math.random() * 2), vy: Math.sin(a) * (1 + Math.random() * 2), life: 20 + Math.random() * 12, color }); } }
  // 하늘·수평선·바다를 나누고, 파도는 오른쪽에서 왼쪽으로 계속 흐릅니다.
  function sea(now) {
    const horizon = 108;
    const sky = ctx.createLinearGradient(0, 0, 0, horizon); sky.addColorStop(0, course.sky[0]); sky.addColorStop(1, course.sky[1]); ctx.fillStyle = sky; ctx.fillRect(0, 0, canvas.width, horizon);
    const ocean = ctx.createLinearGradient(0, horizon, 0, canvas.height); ocean.addColorStop(0, course.sea[0]); ocean.addColorStop(1, course.sea[1]); ctx.fillStyle = ocean; ctx.fillRect(0, horizon, canvas.width, canvas.height - horizon);
    ctx.fillStyle = '#fff9'; ctx.beginPath(); ctx.arc(88, 57, 25, 0, Math.PI * 2); ctx.fill();
    // 먼 바다의 수평선과 파도 거품
    ctx.strokeStyle = '#ffffffcc'; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(0, horizon); ctx.lineTo(canvas.width, horizon); ctx.stroke();
    const layers = [{ y: 145, a: 4, w: 85, alpha: '#ffffff66' }, { y: 230, a: 6, w: 105, alpha: '#d9f8ff82' }, { y: 325, a: 8, w: 125, alpha: '#ffffff5c' }, { y: 415, a: 10, w: 145, alpha: '#d5f8ff70' }];
    layers.forEach((layer, index) => { ctx.strokeStyle = layer.alpha; ctx.lineWidth = 2 + index; ctx.beginPath(); for (let x = -20; x <= canvas.width + 20; x += 8) { const y = layer.y + Math.sin((x + now * .22) / layer.w) * layer.a; x === -20 ? ctx.moveTo(x, y) : ctx.lineTo(x, y); } ctx.stroke(); });
    // 작은 하이라이트도 왼쪽으로 이동해 바다의 흐름을 더해 줍니다.
    ctx.fillStyle = '#ffffff50'; for (let row = 0; row < 4; row++) { const y = 175 + row * 74; for (let x = -50; x < canvas.width + 110; x += 155) { ctx.beginPath(); ctx.ellipse(x - (now / 10 % 155), y, 34, 3, 0, 0, Math.PI * 2); ctx.fill(); } }
    ctx.fillStyle = '#07577d'; ctx.font = 'bold 14px system-ui'; ctx.textAlign = 'left'; ctx.fillText('BUSAN SURF CLEAN-UP', 18, 28); ctx.textAlign = 'right'; ctx.fillText('MOVE ↑ ↓ ← →  /  TRASH +5', canvas.width - 18, 28);
  }
  function jelly(x, y) { ctx.save(); ctx.translate(x, y); ctx.fillStyle = '#f38abbdc'; ctx.beginPath(); ctx.arc(0, -4, 20, Math.PI, 0); ctx.lineTo(20, 8); ctx.lineTo(-20, 8); ctx.closePath(); ctx.fill(); ctx.strokeStyle = '#9c4e80'; ctx.lineWidth = 2; for (let i = -12; i <= 12; i += 8) { ctx.beginPath(); ctx.moveTo(i, 8); ctx.quadraticCurveTo(i - 7, 18, i + 2, 27); ctx.stroke(); } ctx.fillStyle = '#553553'; ctx.beginPath(); ctx.arc(-7, -3, 2, 0, Math.PI * 2); ctx.arc(7, -3, 2, 0, Math.PI * 2); ctx.fill(); ctx.restore(); }
  // 끝부분이 안쪽으로 말린 갈고리 형태의 옆모습 파도입니다.
  function waveObstacle(x, y) { ctx.save(); ctx.translate(x, y); ctx.fillStyle = '#159fd0'; ctx.beginPath(); ctx.moveTo(-52, 28); ctx.quadraticCurveTo(-40, -17, -10, -18); ctx.quadraticCurveTo(11, -54, 37, -19); ctx.quadraticCurveTo(53, 5, 32, 17); ctx.quadraticCurveTo(20, 24, 10, 11); ctx.quadraticCurveTo(23, 5, 15, -7); ctx.quadraticCurveTo(5, -17, -5, -1); ctx.quadraticCurveTo(-21, 24, -52, 28); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#eaffff'; ctx.beginPath(); ctx.moveTo(-43, 17); ctx.quadraticCurveTo(-27, -24, 2, -25); ctx.quadraticCurveTo(23, -25, 30, -8); ctx.quadraticCurveTo(34, 3, 17, 3); ctx.quadraticCurveTo(22, -12, 6, -13); ctx.quadraticCurveTo(-14, -12, -27, 14); ctx.closePath(); ctx.fill(); ctx.strokeStyle = '#08769d'; ctx.lineWidth = 3; ctx.stroke(); ctx.restore(); }
  function trash(item) { ctx.save(); ctx.translate(item.x, item.y); if (item.kind === 'bottle') { ctx.fillStyle = '#dff8ff'; ctx.fillRect(-8, -18, 16, 34); ctx.fillStyle = '#2aa7ce'; ctx.fillRect(-7, -6, 14, 12); ctx.fillStyle = '#125c83'; ctx.fillRect(-4, -23, 8, 6); } else if (item.kind === 'can') { ctx.fillStyle = '#e6edf1'; ctx.fillRect(-11, -16, 22, 31); ctx.fillStyle = '#8da0aa'; ctx.beginPath(); ctx.ellipse(0, -16, 11, 4, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#f4b740'; ctx.fillRect(-11, -2, 22, 8); } else { ctx.fillStyle = '#f7e3ffcc'; ctx.beginPath(); ctx.moveTo(-17, -15); ctx.quadraticCurveTo(0, -22, 17, -15); ctx.lineTo(13, 18); ctx.lineTo(-14, 17); ctx.closePath(); ctx.fill(); ctx.strokeStyle = '#9c78a8'; ctx.stroke(); } ctx.restore(); }
  // 흰 원, 눈 두 개, 노란 부리만으로 만든 아주 단순한 기러기 서퍼입니다.
  function surfer() { ctx.save(); ctx.translate(player.x, player.y); ctx.fillStyle = '#f7c448'; ctx.beginPath(); ctx.ellipse(0, 24, 45, 8, 0, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#fff'; ctx.lineWidth = 2; ctx.stroke(); ctx.fillStyle = '#ffffff'; ctx.strokeStyle = '#466b80'; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(0, -6, 27, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#193748'; ctx.beginPath(); ctx.arc(-5, -12, 3, 0, Math.PI * 2); ctx.arc(10, -12, 3, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#f6bd32'; ctx.strokeStyle = '#d88c14'; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(14, -7); ctx.lineTo(29, -2); ctx.lineTo(14, 4); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.restore(); }
  function draw(now) { sea(now); objects.forEach(item => item.kind === 'jelly' ? jelly(item.x, item.y) : item.kind === 'wave' ? waveObstacle(item.x, item.y) : trash(item)); particles.forEach(p => { ctx.fillStyle = p.color; ctx.globalAlpha = p.life / 32; ctx.fillRect(p.x - 2, p.y - 2, 4, 4); ctx.globalAlpha = 1; }); surfer(); if (flashLife) { ctx.fillStyle = '#fff'; ctx.font = 'bold 21px system-ui'; ctx.textAlign = 'center'; ctx.fillText(flash, player.x, player.y - 48 - (28 - flashLife) * .7); } }
  function end(reason) { stop(); const best = Math.max(Number(localStorage.seaSurfBest || 0), score); localStorage.seaSurfBest = best; $('gameOverTitle').textContent = reason === 'wave' ? '높은 파도에 휩쓸렸어요' : '해파리와 부딪혔어요'; $('gameOverMessage').textContent = `점수 ${score}점 · 쓰레기 ${collected}개 수거 · 최고 점수 ${best}점`; $('gameOver').classList.remove('hidden'); beep(160); }
  return { init, choose, start, stop, backToChoices };
})();
